package com.clouddubber.infra.persistence;

import com.clouddubber.domain.model.DubbingJob;
import com.clouddubber.domain.model.DubbingSegment;
import com.clouddubber.domain.model.Enums;
import com.clouddubber.domain.model.VoiceProfile;
import com.clouddubber.domain.port.Ports;
import jakarta.persistence.Entity;import jakarta.persistence.Id;import jakarta.persistence.Table;
import java.time.Instant;import java.util.List;import java.util.Optional;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Entity @Table(name="dubbing_jobs") class DubbingJobEntity { @Id public String id; public String originalFilename; public String contentType; public String sourceType; public String sourceAsset; public String extractedAudioAsset; public String originalTranscriptAsset; public String translatedScriptAsset; public String dubbedAudioAsset; public String renderedVideoAsset; public String failureReason; public String status; public Instant createdAt; public Instant updatedAt; }
@Entity @Table(name="dubbing_segments") class DubbingSegmentEntity { @Id public String id; public String jobId; public Integer segmentIndex; public Double startTime; public Double endTime; public String originalText; public String translatedText; public String adaptedText; public String status; public String failureReason; }
@Entity @Table(name="voice_profiles") class VoiceProfileEntity { @Id public String id; public String displayName; public boolean consentAccepted; public String status; public Instant createdAt; }

interface SpringJobRepo extends JpaRepository<DubbingJobEntity,String> { List<DubbingJobEntity> findByStatusOrderByCreatedAtAsc(String status, org.springframework.data.domain.Pageable pageable); }
interface SpringSegRepo extends JpaRepository<DubbingSegmentEntity,String> { List<DubbingSegmentEntity> findByJobIdOrderBySegmentIndexAsc(String jobId); boolean existsByJobIdAndSegmentIndex(String jobId, Integer segmentIndex); }
interface SpringVoiceRepo extends JpaRepository<VoiceProfileEntity,String> {}

@Repository class JpaDubbingJobRepository implements Ports.DubbingJobRepository { private final SpringJobRepo repo; JpaDubbingJobRepository(SpringJobRepo repo){this.repo=repo;} public DubbingJob save(DubbingJob j){ DubbingJobEntity e=repo.findById(j.id).orElse(new DubbingJobEntity()); e.id=j.id;e.originalFilename=j.originalFileName;e.contentType=j.originalContentType;e.sourceType=j.sourceType.name();e.sourceAsset=j.sourceAsset;e.extractedAudioAsset=j.extractedAudioAsset;e.originalTranscriptAsset=j.originalTranscriptAsset;e.translatedScriptAsset=j.translatedScriptAsset;e.dubbedAudioAsset=j.dubbedAudioAsset;e.renderedVideoAsset=j.renderedVideoAsset;e.failureReason=j.failureReason;e.status=j.status.name();e.createdAt=j.createdAt;e.updatedAt=j.updatedAt; repo.save(e); return j;} public Optional<DubbingJob> findById(String id){ return repo.findById(id).map(this::map); } public List<DubbingJob> search(int page,int size){ return repo.findAll(PageRequest.of(page,size)).stream().map(this::map).toList(); } public List<DubbingJob> findByStatus(Enums.DubbingJobStatus status, int limit){ return repo.findByStatusOrderByCreatedAtAsc(status.name(), PageRequest.of(0, limit)).stream().map(this::map).toList(); } private DubbingJob map(DubbingJobEntity e){ return new DubbingJob(e.id,e.originalFilename,e.contentType,Enums.DubbingSourceType.valueOf(e.sourceType),Enums.DubbingJobStatus.valueOf(e.status),e.sourceAsset,e.extractedAudioAsset,e.originalTranscriptAsset,e.translatedScriptAsset,e.dubbedAudioAsset,e.renderedVideoAsset,e.failureReason,e.createdAt,e.updatedAt); }}
@Repository class JpaDubbingSegmentRepository implements Ports.DubbingSegmentRepository { private final SpringSegRepo repo; JpaDubbingSegmentRepository(SpringSegRepo repo){this.repo=repo;} public List<DubbingSegment> findByJobId(String jobId){ return repo.findByJobIdOrderBySegmentIndexAsc(jobId).stream().map(e->new DubbingSegment(e.id,e.jobId,e.segmentIndex,e.startTime,e.endTime,e.originalText,e.translatedText,e.adaptedText,Enums.DubbingSegmentStatus.valueOf(e.status),e.failureReason)).toList(); } public Optional<DubbingSegment> findById(String id){ return repo.findById(id).map(e->new DubbingSegment(e.id,e.jobId,e.segmentIndex,e.startTime,e.endTime,e.originalText,e.translatedText,e.adaptedText,Enums.DubbingSegmentStatus.valueOf(e.status),e.failureReason)); } public DubbingSegment save(DubbingSegment s){ DubbingSegmentEntity e=repo.findById(s.id).orElse(new DubbingSegmentEntity()); e.id=s.id;e.jobId=s.jobId;e.segmentIndex=s.segmentIndex;e.startTime=s.startTime;e.endTime=s.endTime;e.originalText=s.originalText;e.translatedText=s.translatedText;e.adaptedText=s.adaptedText;e.status=s.status.name();e.failureReason=s.failureReason; repo.save(e); return s; } public boolean existsByJobIdAndSegmentIndex(String jobId, int segmentIndex){ return repo.existsByJobIdAndSegmentIndex(jobId, segmentIndex); }}
@Repository class JpaVoiceProfileRepository implements Ports.VoiceProfileRepository { private final SpringVoiceRepo repo; JpaVoiceProfileRepository(SpringVoiceRepo repo){this.repo=repo;} public VoiceProfile save(VoiceProfile v){ VoiceProfileEntity e=new VoiceProfileEntity(); e.id=v.id;e.displayName=v.displayName;e.consentAccepted=v.consentAccepted;e.status=v.status.name();e.createdAt=v.createdAt; repo.save(e); return v;} public Optional<VoiceProfile> findById(String id){ return repo.findById(id).map(e->new VoiceProfile(e.id,e.displayName,e.consentAccepted,Enums.VoiceProfileStatus.valueOf(e.status),e.createdAt)); }}
