spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cloud_dubber}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health
springdoc:
  swagger-ui:
    path: /swagger-ui.html
