spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clouddubber
    username: clouddubber
    password: clouddubber
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
