package com.localdubber.domain.model

enum class DubbingProjectStatus { CREATED, WAITING_FOR_EXTRACTION, EXTRACTING_AUDIO, WAITING_FOR_TRANSCRIPTION, TRANSCRIBING, WAITING_FOR_TRANSLATION, TRANSLATING, WAITING_FOR_VOICE_GENERATION, GENERATING_VOICE, WAITING_FOR_RENDERING, RENDERING, COMPLETED, FAILED }
